<h2>Sign up</h2>

<?php echo $this->tag->form("signup/register"); ?>

    <p>
        <label for="name">Name</label>
        <?php echo $this->tag->textField("name"); ?>
    </p>

    <p>
        <label for="login">Login</label>
        <?php echo $this->tag->textField("login"); ?>
    </p>

    <p>
        <label for="password">Password</label>
        <?php echo $this->tag->textField("password"); ?>
    </p>


    <p>
        <?php echo $this->tag->submitButton("Registr"); ?>
    </p>

</form>