<?php
echo $this->tag->form(
[
"admin/create",
"autocomplete" => "off",
"class" => "form",
"enctype" => "multipart/form-data"
]);
?>
<h2 class="form-heading">Create form</h2>
<div class="container">
<div class="row">
<div class="col-3">
<?php echo $form->label("name"); ?>
</div>
<div class="col-9">
<?php echo $form->render("name")."<br>".$form->messages('name'); ?>
</div>
</div>
<hr>
<div class="row">
<div class="col-3">
<?php echo $form->label("status"); ?>
</div>
<div class="col-9" style="text-align: left;">
<?php echo $form->render("status")."<br>".$form->messages('status'); ?>
</div>
</div>
<hr>
<div class="row">
<div class="col-3">
<?php echo $form->label("url"); ?>
</div>
<div class="col-9">
<?php echo $form->render("url")."<br>".$form->messages('url'); ?>
</div>
</div>
<hr>
<div class="row">
<div class="col-3">
<label id="file" class="input-block-level">File:</label>
</div>
<div class="col-9 right">
<div class="custom-file">
<input type="file" class="custom-file-input" id="customFile" name="image" required>
<label class="custom-file-label" for="customFile"></label>
</div>
</div>
</div>
<br>
<div class="row">
<div class="col-6">
<input class="btn btn-large btn-dark input-block-level" name="cancel" type="button" onclick="window.location.replace('/banner/admin/')" value="Cancel">
</div>
<div class="col-6 right">
<input class="btn btn-large btn-dark input-block-level" name="submit" type="submit" value="Create">
</div>
</div>
</div>

<?php echo $form->render("csrf", ['value' => $this->security->getToken()]); ?>

<?php echo $this->tag->endForm(); ?>
