<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<br>

<div>
    <h1>
    Banners
    </h1>
    <p>
        <?php echo $this->tag->linkTo([BASE_URL . "admin/new", "Create banners", "class" => "btn btn-primary"]) ?>
        <?php echo $this->tag->linkTo([BASE_URL . "admin/search", "Search", "class" => "btn btn-primary"]) ?>
    </p>
</div>

<?php
if ($users->count() > 0): ?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th>№</th>
            <th>Id</th>
            <th>Name</th>
            <th>Login</th>
            <th>Password</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="3">Users quantity: <?php echo $users->count(); ?></td>
        </tr>
        </tfoot>
        <tbody>
        <?php
        $iter = 0;
        foreach ($users as $user):
            $iter++; ?>
            <tr>
                <td><?php echo $iter; ?></td>
                <td><?php echo $user->id; ?></td>
                <td><?php echo $user->name; ?></td>
                <td><?php echo $user->login; ?></td>
                <td><?php echo $user->password; ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>
<br>
<?php
if ($banners->count() > 0): ?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th>№</th>
            <th>Id</th>
            <th>Name</th>
            <th>Status</th>
            <th>Position</th>
            <th></th>
            <th></th>
            <th>Image</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="3">Banners quantity: <?php echo $banners->count(); ?></td>
        </tr>
        </tfoot>
        <tbody>
        <?php
        $iter = 0;
        foreach ($banners as $banner):
            $iter++; ?>
            <tr>
                <td><?php echo $iter; ?></td>
                <td><?php echo $banner->id; ?></td>
                <td><?php echo $banner->name; ?></td>
                <td><?php echo $banner->status; ?></td>
                <td><?php echo $banner->position; ?></td>
                <td><?php echo $this->tag->linkTo(["admin/delete/" . $banner->id, "Delete"]); ?></td>
                <td><?php echo $this->tag->linkTo(["admin/edit/" . $banner->id, "Edit"]); ?></td>
                <td><img src="<?php echo $banner->showImage(); ?>"></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <?php
endif;
?>
