<div>
<?php echo $this->tag->linkTo([BASE_URL . "admin/create", "Create new banner", "class" => "btn btn-dark"]) ?>
</div>
<br>

<h1>
Banners
</h1>
<link href="<?php echo htmlspecialchars(CSS_URL . "datatable/datatablesnew.min.css"); ?>" rel="stylesheet">
<link rel="stylesheet" href="<?php echo htmlspecialchars(CSS_URL . "mystyle/table.css"); ?>">

<script type="text/javascript" src="<?php echo htmlspecialchars(JS_URL . "datatable/datatables.min.js"); ?>"></script>

<script type="text/javascript">
$(document).ready(function () {
$('#dtBasicExample').DataTable({
    "pagingType": "full_numbers",
    "lengthMenu": [[2, 5, 10, -1], [2, 5, 10, "All"]],
    "pageLength": 5,
    "columns": [
        null,
        null,
        null,
        null,
        null,
        null,
        { "orderable": false },
        { "orderable": false },
        { "orderable": false },
    ]
});
$('.dataTables_length').addClass('bs-select');
});
</script>

<table id="dtBasicExample" class="table table-striped table-bordered" cellspacing="0" width="100%">
<thead>
<tr>
<th><?php echo $this->tag->linkTo(["admin/index?page=", "First", 'class' => 'page-link']) ?></th>
<th>Name</th>
<th>Image Location</th>
<th >Link</th>
<th>Status</th>
<th>Position</th>
<th>Image</th>
<th>Edit</th>
<th>Delete</th>
</tr>
</thead>
<tbody>
<?php
foreach ($banners as $banner): ?>
<tr class="table-light">
<td id="id" class="longtoshort"><?php echo htmlspecialchars($banner->id); ?></td>
<td id="name" class="longtoshort"><?php echo htmlspecialchars($banner->name); ?></td>
<td id="image" class="longtoshort"><?php echo htmlspecialchars($banner->image); ?></td>
<td id="url" class="longtoshort"><?php echo htmlspecialchars($banner->url); ?></td>
<td id="status"><?php echo htmlspecialchars($banner->status); ?></td>
<td id="position" class="longtoshort"><?php echo htmlspecialchars($banner->position); ?></td>
<td id="img"><img src="<?php echo IMG_URL . htmlspecialchars($banner->image); ?>"  height="100%"></td>
<td id="delete"><?php echo $this->tag->linkTo(["admin/edit/" . htmlspecialchars($banner->id), "Edit", "class" => "btn btn-large btn-secondary"]); ?></td>
<td id="delete"><?php echo $this->tag->linkTo(["admin/delete/" . htmlspecialchars($banner->id), "Delete", "class" => "btn btn-large btn-secondary"]); ?></td>
</tr>
<?php endforeach; ?>
</tbody>
<div class="row">
<div class="col-sm-1">
<p class="pagination" style="line-height: 1.42857; padding: 6px 12px;">
<?php echo $page->current, "/", $page->total_pages ?>
</p>
</div>
<div class="col-sm-11">
<nav>
<ul class="pagination">
<li><?php echo $this->tag->linkTo(["admin/index", "First", 'class' => 'page-link']) ?></li>
<li><?php echo $this->tag->linkTo(["admin/index?page=" . $page->before, "Previous", 'class' => 'page-link']) ?></li>
<li><?php echo $this->tag->linkTo(["admin/index?page=" . $page->next, "Next", 'class' => 'page-link']) ?></li>
<li><?php echo $this->tag->linkTo(["admin/index?page=" . $page->last, "Last", 'class' => 'page-link']) ?></li>
</ul>
</nav>
</div>
</div>
</table>


<br>
<br>
