<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo([BASE_URL . "admin/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo([BASE_URL . "admin/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Url</th>
            <th>Status</th>
            <th>Position</th>
            <th></th>
            <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $banner): ?>
            <tr>
            <td><?php echo $banner->id ?></td>
            <td><?php echo $banner->name ?></td>
            <td><?php echo $banner->url ?></td>
            <td><?php echo $banner->status ?></td>
            <td><?php echo $banner->position ?></td>

            <td><?php echo $this->tag->linkTo(["admin/edit/" . $banner->id, "Edit"]); ?></td>
            <td><?php echo $this->tag->linkTo(["admin/delete/" . $banner->id, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857; padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo(["admin/search", "First", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["admin/search?page=" . $page->before, "Previous", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["admin/search?page=" . $page->next, "Next", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["admin/search?page=" . $page->last, "Last", 'class' => 'page-link']) ?></li>
            </ul>
        </nav>
    </div>
</div>
