<h1>
Users
</h1>
<link href="<?php echo htmlspecialchars(CSS_URL . "datatable/datatablesnew.min.css"); ?>" rel="stylesheet">
<link rel="stylesheet" href="<?php echo htmlspecialchars(CSS_URL . "mystyle/table.css"); ?>">

<script type="text/javascript" src="<?php echo htmlspecialchars(JS_URL . "datatable/datatables.min.js"); ?>"></script>
<script type="text/javascript">
$(document).ready(function () {
$('#dtBasicExample').DataTable({
    "pagingType": "full_numbers",
    "lengthMenu": [[2, 5, 10, -1], [2, 5, 10, "All"]],
    "pageLength": 5,
});
$('.dataTables_length').addClass('bs-select');
});
</script>

<table id="dtBasicExample" class="table table-striped table-bordered" cellspacing="0" width="100%">
<thead>
<tr>
<th>Id</th>
<th>Name</th>
<th>Login</th>
<th>Password</th>
<th>Status</th>
</tr>
</thead>
<tbody>
<?php
foreach ($users as $user): ?>
<tr class="table-light">
<td><?php echo htmlspecialchars($user->id); ?></td>
<td><?php echo htmlspecialchars($user->name); ?></td>
<td><?php echo htmlspecialchars($user->login); ?></td>
<td><?php echo htmlspecialchars($user->password); ?></td>
<td><?php echo htmlspecialchars($user->status); ?></td>
</tr>
<?php endforeach; ?>
</tbody>
<tfoot>
<tr>
<th>Id</th>
<th>Name</th>
<th>Login</th>
<th>Password</th>
<th>Status</th>
</tr>
</tfoot>
</table>
<br>
<br>
