<style>
.flex-direction-nav a {
  line-height: 40px;
}
</style>
<section class="slider">
<div class="flexslider">
<ul class="slides">
<?php
foreach ($banners as $banner): ?>
<li><img src="<?php echo $banner->showImage(); ?>"></li>
<?php endforeach;
?>
</ul>
</div>
</section>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
<script defer src="<?php echo htmlspecialchars(JS_URL . "flexslider/jquery.flexslider.js"); ?>"></script>
<script>
  $(window).load(function(){
    $('.flexslider').flexslider({
        animation: "slide",
        slideshow: true,
        slideshowSpeed: 4000,
        pauseOnAction: true,
        pauseOnHover: true,
    });
  });
</script>
