<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="Cache-Control" content="no-cache">
<title>Phalcon Tutorial</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
<link rel="stylesheet" href="<?php echo htmlspecialchars(CSS_URL . "flexslider/flexslider.css"); ?>">
<!-- <link rel="stylesheet" href="<?php echo htmlspecialchars(CSS_URL . "bootstrap/bootstrap.css"); ?>"> -->

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

<style type="text/css">
  body {
    background-color: #f5f5f5;
  }
  .navbar {
    margin-bottom: 30px;
  }
</style>
</head>

<body>
<div class="jumbotron text-center" style="margin-bottom: 0">
</div>

<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
<span class="navbar-brand">Navbar</span>

<div class="collapse navbar-collapse" id="collapsibleNavbar">
<ul class="navbar-nav mr-auto">
<li class="nav-item">
<?php echo $this->tag->linkTo([BASE_URL, "Home", 'class' => 'nav-link']); ?>
</li>
<li class="nav-item">
<?php echo $this->tag->linkTo([BASE_URL . "admin", "Admin panel", 'class' => 'nav-link']); ?>
</li>
</ul>
<ul class="navbar-nav">
<?php if  ($this->session->has('loggedin') && $this->session->get('loggedin')): ?>
<li class="nav-item">
<span class="nav-link active">Welcome <?php echo htmlspecialchars($this->session->get('user_name')) ?></span>
</li>
<li class="nav-item">
<?php echo $this->tag->linkTo([BASE_URL . "session/signout", "Sign out", 'class' => 'nav-link']);
else: ?>
</li>
<li class="nav-item">
<?php echo $this->tag->linkTo([BASE_URL . "session/signup", "Sign up", 'class' => 'nav-link']); ?>
</li>
<li class="nav-item">
<?php echo $this->tag->linkTo([BASE_URL . "session/signin", "Sign in", 'class' => 'nav-link']);
endif; ?>
</li>
</ul>
</div>
</nav>
<?php echo $this->getContent(); ?>
<!-- <div class="jumbotron text-center" style="margin-top: 30px;">
</div> -->
</body>
</html>
